#!/bin/bash
# Markdown -> PDF conversion script (Nuwa Book Forge)
# Dependencies: pandoc (required), xelatex (recommended for CJK support)
#
# Usage:
#   bash build_pdf.sh <input.md> <output.pdf>
#
# Example:
#   bash build_pdf.sh output/rag-book/manuscript.md output/rag-book/manuscript.pdf

set -e

INPUT="$1"
OUTPUT="$2"

if [ -z "$INPUT" ] || [ -z "$OUTPUT" ]; then
    echo "Usage: bash build_pdf.sh <input.md> <output.pdf>"
    exit 1
fi

if [ ! -f "$INPUT" ]; then
    echo "Error: File not found: $INPUT"
    exit 1
fi

# Check pandoc
if ! command -v pandoc &> /dev/null; then
    echo "Error: pandoc not installed"
    echo "Install: brew install pandoc"
    exit 1
fi

# Check xelatex
HAS_XELATEX=false
if command -v xelatex &> /dev/null; then
    HAS_XELATEX=true
fi

# Script directory
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ "$HAS_XELATEX" = true ]; then
    echo "Using xelatex engine (CJK support enabled)..."

    # Create temporary LaTeX template
    TEMP_TEMPLATE=$(mktemp /tmp/nuwa-book-template.XXXXXX.tex)
    cat > "$TEMP_TEMPLATE" << 'TEMPLATE_EOF'
\documentclass[12pt,a4paper]{article}

% === CJK support ===
\usepackage{ctex}
\usepackage{fontspec}

% === Page layout ===
\usepackage[margin=2.5cm]{geometry}
\usepackage{indentfirst}
\usepackage{parskip}

% === TOC ===
\usepackage{hyperref}
\hypersetup{
    colorlinks=true,
    linkcolor=blue!70!black,
    urlcolor=blue!60!black,
    citecolor=green!50!black,
    bookmarks=true,
    bookmarksnumbered=true,
    pdfauthor={Nuwa Book Forge},
}

% === Code highlighting ===
\usepackage{listings}
\lstset{
    basicstyle=\ttfamily\small,
    breaklines=true,
    frame=single,
    numbers=left,
    numberstyle=\tiny\color{gray},
    keywordstyle=\color{blue},
    commentstyle=\color{green!60!black},
    stringstyle=\color{red!70!black},
    showstringspaces=false,
    tabsize=2,
}

% === Tables ===
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}

% === Images ===
\usepackage{graphicx}

% === Headers and footers ===
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\leftmark}
\fancyhead[R]{\thepage}
\renewcommand{\headrulewidth}{0.4pt}

% === Title formatting ===
\usepackage{titlesec}
\titleformat{\section}{\Large\bfseries}{\thesection}{1em}{}
\titleformat{\subsection}{\large\bfseries}{\thesubsection}{1em}{}
\titleformat{\subsubsection}{\normalsize\bfseries}{\thesubsubsection}{1em}{}

% === Title info ===
$if(title)$
\title{\Huge\textbf{$title$}}
$endif$
$if(subtitle)$
\subtitle{$subtitle$}
$endif$
$if(date)$
\date{$date$}
$endif$
$if(author)$
\author{$author$}
$endif$

\begin{document}

% === Cover page ===
\begin{titlepage}
\centering
\vspace*{3cm}
{\Huge\textbf{$title$}}

$if(subtitle)$
\vspace{1cm}
{\Large $subtitle$}
$endif$

\vspace{2cm}
{\large $if(author)$$author$$endif$}

\vspace{1cm}
{\large $if(date)$$date$$endif$}

\vfill
{\small Generated by Nuwa Book Forge}
\end{titlepage}

% === Table of contents ===
\tableofcontents
\newpage

$body$

\end{document}
TEMPLATE_EOF

    pandoc "$INPUT" \
        -o "$OUTPUT" \
        --pdf-engine=xelatex \
        --template="$TEMP_TEMPLATE" \
        --toc \
        --toc-depth=3 \
        --highlight-style=tango \
        --wrap=preserve \
        2>&1

    PDF_EXIT=$?

    rm -f "$TEMP_TEMPLATE"

    if [ $PDF_EXIT -eq 0 ]; then
        echo "PDF generated successfully: $OUTPUT"
    else
        echo "PDF generation failed (exit code: $PDF_EXIT)"
        echo "Common fixes:"
        echo "  - Missing CJK fonts: brew install --cask font-noto-sans-cjk"
        echo "  - Missing LaTeX packages: brew install --cask mactex-no-gui"
        exit 1
    fi

else
    echo "Warning: xelatex not installed, using pandoc default engine..."
    echo "  CJK characters may not render correctly."
    echo "  Install xelatex: brew install --cask mactex-no-gui"
    echo ""

    pandoc "$INPUT" \
        -o "$OUTPUT" \
        --toc \
        --toc-depth=3 \
        --highlight-style=tango \
        --wrap=preserve \
        2>&1

    if [ $? -eq 0 ]; then
        echo "PDF generated (CJK rendering may be broken): $OUTPUT"
    else
        echo "PDF generation failed"
        echo "Install full LaTeX support: brew install --cask mactex-no-gui"
        exit 1
    fi
fi
